name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init -reconfigure

      - name: Plan infrastructure
        run: terraform plan -out=tfplan

      - name: Apply infrastructure
        run: terraform apply -auto-approve tfplan
