name: Static Code Analysis

on:
  pull_request:
    paths:
      - 'infra/**/*.tf'
    types: [opened, synchronize, reopened]

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Format Terraform code
        run: terraform fmt -check -diff

      - name: Validate Terraform configuration
        run: terraform validate
